// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace AppFirst;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"AppFirst.Views.HomeLandingPage", typeof(AppFirst.Views.HomeLandingPage)},
        {"AppFirst.Views.Sample1Page", typeof(AppFirst.Views.Sample1Page)},
        {"AppFirst.Views.Pages.SamplePage", typeof(AppFirst.Views.Pages.SamplePage)},
        {"AppFirst.Views.Pages.LoadSqlDataPage", typeof(AppFirst.Views.Pages.LoadSqlDataPage)},
        {"AppFirst.Views.Pages.LoadSqlDataGridPage", typeof(AppFirst.Views.Pages.LoadSqlDataGridPage)},
        {"AppFirst.Views.Pages.LoadSqlDataSqlitePage", typeof(AppFirst.Views.Pages.LoadSqlDataSqlitePage)},
    };
}
